apiVersion: apps/v1
kind: Deployment
metadata:
  name: papotecar
  namespace: default
  labels:
    app: papotecar
spec:
  replicas: 1
  selector:
    matchLabels:
      app: papotecar
  template:
    metadata:
      labels:
        app: papotecar
    spec:
      containers:
      - name: app
        image: ghcr.io/nkirchhoffer/peperecar:main
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: POSTGRESQL_URL
          valueFrom:
            secretKeyRef:
              name: postgres
              key: url
        - name: POSTGRESQL_USERNAME
          valueFrom:
            secretKeyRef:
              name: postgres
              key: username
        - name: POSTGRESQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres
              key: password
      - name: postgresdb
        image: postgres:latest
        env:
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres
                key: password
          - name: PGDATA
            value: "/var/lib/postgresql/data/pgdata"
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgresql
      imagePullSecrets:
      - name: regcred