apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog-staging
  namespace: default
  labels:
    app: blog-staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blog-staging
  template:
    metadata:
      labels:
        app: blog-staging
    spec:
      containers:
      - name: blog
        image: ghcr.io/clebard-cloud/blog:develop-df7cf4d835b91783d53aa6b4619670d2394ae56d-12
        ports:
        - containerPort: 80