apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog-staging
  namespace: default
  labels:
    app: blog-staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blog-staging
  template:
    metadata:
      labels:
        app: blog-staging
    spec:
      containers:
      - name: blog
        image: ghcr.io/clebard-cloud/blog:develop-970bddbed35c4b5ea7f3870b14a3fc442199ee94-11
        ports:
        - containerPort: 80